---
name: "Run linters"
description: "Runs our Go linters"

runs:
  using: "composite"
  steps:
    - name: Install Task
      run: go generate -x
      working-directory: tools
      shell: bash

    - name: Run init
      run: bin/task init
      shell: bash

    - name: Format code
      run: bin/task fmt
      shell: bash

    # exit early to prevent confusion from linters checking the changed code
    - name: Check dirty
      run: |
        git status
        git diff --exit-code
      shell: bash

    - name: Run linters
      run: bin/task lint
      shell: bash

    - name: Check dirty
      run: |
        git status
        git diff --exit-code
      shell: bash
