---
name: 'Run linters'
description: 'Runs our linters.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: FerretDB/github-actions/setup-go@main
      with:
        cache-key: lint

    - name: Install Task
      run: go generate -x
      working-directory: tools
      shell: bash

    - name: Run init
      run: bin/task init
      shell: bash

    - name: Format code
      run: bin/task fmt
      shell: bash

    - name: Run required linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45 # sync with tools/go.mod
        args: --config=.golangci-required.yml
        only-new-issues: false
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Run all linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45 # sync with tools/go.mod
        args: --config=.golangci.yml
        only-new-issues: true
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Run linters manually
      run: bin/task lint
      shell: bash

      # TODO don't forget to run go-consistent when we switch back to golangci/golangci-lint-action

    - name: Check dirty
      run: |
        git status
        git diff --exit-code
      shell: bash
