---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [deps]
    assignees: [AlekSi]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [deps]
    assignees: [AlekSi]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/tools"
    labels: [deps]
    assignees: [AlekSi]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
