---
name: "Conform PR"
description: "Checks that PR conforms to our process guides"

runs:
  using: "composite"
  steps:
    - name: Conform PR
      run: go mod download; go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
