---
# New or experimental linters that should pass (or be reconfigured) for new code.

run:
  timeout: 2m

linters-settings:
  staticcheck:
    go: "1.18"
    checks: ["all"]

linters:
  disable-all: true # TODO
  enable:
    - staticcheck

issues:
  exclude-use-default: false
