---
version: 3

tasks:
  # invoked when `task` is run without arguments
  default:
    deps: [all]

  all:
    desc: "Format and lint code"
    cmds:
      - task: fmt
      - task: lint

  init-tools:
    dir: tools
    cmds:
      - go mod tidy
      - go mod verify
      - go generate -x

  init:
    desc: "Install development tools"
    deps: [init-tools]
    cmds:
      - go mod tidy
      - go mod verify

  init-clean:
    desc: "Clean all caches and re-install development tools"
    cmds:
      - bin/golangci-lint cache clean
      - go clean -cache -testcache -modcache -fuzzcache
      - task: init

  fmt:
    desc: "Format code"
    cmds:
      - bin/goimports{{exeExt}} -format-only -local=github.com/FerretDB/github-actions -w .
      - bin/gofumpt{{exeExt}} -w .

  lint:
    desc: "Run linters"
    deps:
      - lint-golangci-lint
      - lint-go-sumtype
    cmds:
      - bin/golangci-lint run --config=.golangci-new.yml --new-from-rev=main

  lint-golangci-lint:
    cmds:
      - bin/golangci-lint run --config=.golangci.yml

  lint-go-sumtype:
    cmds:
      - bin/go-sumtype ./...

  godocs:
    desc: "Serve godoc documentation at http://127.0.0.1:6060/pkg/github.com/FerretDB/github-actions/?m=all"
    cmds:
      - bin/godoc -http=127.0.0.1:6060
