---
name: "Extract Docker tag"
description: "Extracts Docker tag from the Git and GitHub meta-information"
outputs:
  images:
    description: "Extracted Docker images, e.g. `ghcr.io/ferretdb/ferretdb:0.1.0,ghcr.io/ferretdb/ferretdb:latest`"
    value: ${{ steps.extract.outputs.images }}
  dev:
    description: "Set to `true` for development builds (PRs, branches, pre-release tags), `false` for release builds"
    value: ${{ steps.extract.outputs.dev }}
  ghcr_images:
    description: "The same as images; deprecated."
    value: ${{ steps.extract.outputs.images }}

runs:
  using: "composite"
  steps:
    - name: Extract Docker tag
      id: extract
      run: go mod download; go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
