---
name: "Extract Docker tag"
description: "Extracts Docker tag from the Git and GitHub meta-information"
outputs:
  owner:
    description: "Extracted Docker image owner, e.g. `ferretdb`"
    value: ${{ steps.extract.outputs.owner }}
  name:
    description: "Extracted Docker image name, e.g. `github-actions-dev`"
    value: ${{ steps.extract.outputs.name }}
  tags:
    description: "Extracted Docker image tags, e.g. `pr-add-features,latest`"
    value: ${{ steps.extract.outputs.tags }}
  ghcr:
    description: "Extracted Docker image ghcr.io address, e.g. `ghcr.io/ferretdb/github-actions-dev:pr-add-features`"
    value: ${{ steps.extract.outputs.ghcr }}
  ghcr_images:
    description: "Extracted Docker image ghcr.io address, e.g. `ghcr.io/ferretdb/github-actions-dev:pr-add-features,ghcr.io/ferretdb/github-actions-dev:latest`"
    value: ${{ steps.extract.outputs.ghcr_images }}

runs:
  using: "composite"
  steps:
    - name: Extract Docker tag
      id: extract
      run: go mod download; go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
