---
name: "Extract Docker tag"
description: "Extracts Docker image tag"
outputs:
  tag:
    description: "Extracted Docker image tag"
    value: ${{ steps.extract.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Extract Docker tag
      id: extract
      run: go run main.go
      shell: bash
