---
name: "Extract Docker image name and tag"
description: "Extracts Docker image name and tag"
outputs:
  image:
    description: "Extracted Docker image name"
    value: ${{ steps.extract.outputs.image }}
  tag:
    description: "Extracted Docker image tag"
    value: ${{ steps.extract.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Extract Docker image name and tag
      id: extract
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
