---
name: "Extract Docker tag"
description: "Extracts Docker image tag"

runs:
  using: "composite"
  steps:
    - name: Test
      run: env
      shell: bash

    - name: Extract Docker tag
      run: go run main.go
      shell: bash
