---
name: "Setup Go"
description: "Installs Go, downloads project's Go modules, and restores build and golangci-lint caches"
inputs:
  cache-key:
    description: "First part of key for restoring cache."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19.5"

    - name: Run tool
      id: run
      run: go mod download; go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.run.outputs.cache_path }}
        key: ${{ inputs.cache-key }}-${{ steps.run.outputs.cache_week }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ steps.run.outputs.cache_week }}-${{ hashFiles('**/go.mod') }}
          ${{ inputs.cache-key }}-${{ steps.run.outputs.cache_week }}

    # we don't want them on CI
    - name: Clean test and fuzz caches
      run: |
        go clean -testcache
        go clean -fuzzcache
      shell: bash
