---
name: "Setup Go"
description: "Installs Go, checks environment, downloads project's Go modules, and restores caches"
inputs:
  cache-key:
    description: "First part of key for restoring cache."
    required: false
  keep-test-cache:
    description: "Do not clean test and fuzz caches."
    required: false
    default: "false"
outputs:
  cache_week:
    description: "Cache week, a part of cache key."
    value: ${{ steps.run.outputs.cache_week }}

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.5"
        cache: false

    - name: Run tool
      id: run
      run: go mod download; go run .
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Restore cache
      if: inputs.cache-key != ''
      uses: actions/cache@v4
      with:
        path: ${{ steps.run.outputs.cache_path }}
        key: ${{ inputs.cache-key }}-${{ steps.run.outputs.cache_week }}-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ steps.run.outputs.cache_week }}-

    - name: Keeping test and fuzz caches
      if: ${{ inputs.keep-test-cache }}
      run: |
        echo "Keeping test and fuzz caches (${{ inputs.keep-test-cache }})"
      shell: bash

    - name: Clean test and fuzz caches
      if: ${{ !inputs.keep-test-cache }}
      run: |
        echo "Cleaning test and fuzz caches (${{ inputs.keep-test-cache }})"
        go clean -testcache -fuzzcache
      shell: bash
