---
name: 'Setup Go'
description: 'Installs Go and restores build/test/module cache.'
inputs:
  cache-key:
    description: 'First part of key for restoring cache.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Get week number
      run: echo WEEK_NUMBER=$(date +%U) >> $GITHUB_ENV
      shell: bash

    - name: Get GOCACHE
      id: get_gocache
      run: echo "::set-output name=gocache::$(go env GOCACHE)"
      shell: bash

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.get_gocache.outputs.gocache }}
        key: ${{ inputs.cache-key }}-${{ env.WEEK_NUMBER }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ env.WEEK_NUMBER }}-${{ hashFiles('**/go.mod') }}
          ${{ inputs.cache-key }}-${{ env.WEEK_NUMBER }}

    # Until we have GOFUZZCACHE (https://github.com/golang/go/issues/48901), or some better solution is found.
    - name: Clear fuzz cache
      run: go clean -fuzzcache
      shell: bash
