---
name: 'Detect matching PR'
description: 'Detects matching PR in FerretDB or dance repository'
outputs:
  owner:
    description: 'Matching PR repository owner, e.g. `FerretDB`'
    value: ${{ steps.detect.outputs.owner }}
  repo:
    description: 'Matching PR repository name, e.g. `dance`'
    value: ${{ steps.detect.outputs.repo }}
  number:
    description: 'Matching PR number, e.g. `47`'
    value: ${{ steps.detect.outputs.number }}
  head_sha:
    description: 'Matching PR latest commit SHA, e.g. `6be1be2dd7ea2dcdb289e678a5d41436acca5b5c`'
    value: ${{ steps.detect.outputs.head_sha }}

runs:
  using: 'composite'
  steps:
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Detect matching PR
      id: detect
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
