---
name: "Detect matching PR"
description: "Detect matching PR"

runs:
  using: "composite"
  steps:
    - name: Detect matching PR
      id: detect
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
