---
name: "Detect matching PR"
description: "Detects matching PR or branch in FerretDB or dance repository"
outputs:
  owner:
    description: "Matched repository owner, e.g. `FerretDB`"
    value: ${{ steps.detect.outputs.owner }}
  repo:
    description: "Matched repository name, e.g. `dance`"
    value: ${{ steps.detect.outputs.repo }}
  branch:
    description: "Matched repository branch, e.g. `main` (empty if matched PR)"
    value: ${{ steps.detect.outputs.branch }}
  number:
    description: "Matched PR number, e.g. `47` (empty if matched branch)"
    value: ${{ steps.detect.outputs.number }}

runs:
  using: "composite"
  steps:
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Detect matching PR
      id: detect
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
