---
name: 'Detect matching PR'
description: 'Detect matching PR'
outputs:
  db_base_owner:
    description: 'PR base database repository owner, e.g. `FerretDB`'
    value: ${{ steps.detect.outputs.db_base_owner }}
  db_base_repo:
    description: 'PR base database repository name, e.g. `FerretDB`'
    value: ${{ steps.detect.outputs.db_base_repo }}
  db_base_branch:
    description: 'PR base database repository branch, e.g. `main`'
    value: ${{ steps.detect.outputs.db_base_branch }}
  db_head_owner:
    description: 'PR head database repository owner, e.g. `AlekSi`'
    value: ${{ steps.detect.outputs.db_head_owner }}
  db_head_repo:
    description: 'PR head database repository name, e.g. `FerretDB`'
    value: ${{ steps.detect.outputs.db_head_repo }}
  db_head_branch:
    description: 'PR head database repository branch, e.g. `feature-branch`'
    value: ${{ steps.detect.outputs.db_head_branch }}

runs:
  using: 'composite'
  steps:
    - name: Detect matching PR
      id: detect
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
