---
name: PR verification
on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: PR verification
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PR verification
        uses: ./pr-verification
